### ISSUE TITLE
Expansion Header Missing

### ISSUE THREAD

**Issue by dylandaigle** [joyja/ignition-framework#3]
The path on the EmbeddedView for the headers in the Expansion Panel/Panel component is trying to point to `Components/Expansion Panel/Test/Header` that is missing from the project.

Is this still a work-in-progress?

![image](https://user-images.githubusercontent.com/71790038/129105122-13a986ad-2cd2-4744-a8f0-e955abc8f974.png)

**Comment by joyja** [comment]
@dylandaigle you probably closed this because you realized this, but I'll explain if others find this (and for future reference) the views for the header and the content of the expansion panels are up to the user to create. It seems like a good point that it may be worth including some example views for them in the framework project though. Thanks for the feedback!
